/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CircleCourtAgreementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptAgreement"
      | "agentA"
      | "agentB"
      | "claimFunds"
      | "claimable"
      | "claimed"
      | "confirmOutcome"
      | "disputeRaisedAt"
      | "escrowAmount"
      | "evidenceRulesHash"
      | "evidenceWindow"
      | "factory"
      | "finalOutcomeHash"
      | "guidelinesHash"
      | "joinDeadlineAt"
      | "juryBridge"
      | "juryVerdictHash"
      | "markEscrowFunded"
      | "metadataUri"
      | "outcomes"
      | "proposeOutcome"
      | "raiseDispute"
      | "statementHash"
      | "status"
      | "submitEvidence"
      | "submitJuryVerdict"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementAccepted"
      | "DisputeRaised"
      | "EscrowFunded"
      | "EvidenceSubmitted"
      | "FundsClaimed"
      | "JuryVerdictSubmitted"
      | "OutcomeConfirmed"
      | "OutcomeProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptAgreement",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "agentA", values?: undefined): string;
  encodeFunctionData(functionFragment: "agentB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmOutcome",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeRaisedAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrowAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceRulesHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceWindow",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalOutcomeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "guidelinesHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "joinDeadlineAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "juryBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "juryVerdictHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markEscrowFunded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "metadataUri",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "outcomes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeOutcome",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "statementHash",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitJuryVerdict",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "acceptAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFunds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeRaisedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceRulesHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalOutcomeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guidelinesHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "joinDeadlineAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "juryBridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "juryVerdictHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markEscrowFunded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metadataUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "outcomes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "statementHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitJuryVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AgreementAcceptedEvent {
  export type InputTuple = [agentB: AddressLike];
  export type OutputTuple = [agentB: string];
  export interface OutputObject {
    agentB: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [actor: AddressLike, reasonUri: string];
  export type OutputTuple = [actor: string, reasonUri: string];
  export interface OutputObject {
    actor: string;
    reasonUri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [agentA: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agentA: string, amount: bigint];
  export interface OutputObject {
    agentA: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceSubmittedEvent {
  export type InputTuple = [actor: AddressLike, evidenceUri: string];
  export type OutputTuple = [actor: string, evidenceUri: string];
  export interface OutputObject {
    actor: string;
    evidenceUri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsClaimedEvent {
  export type InputTuple = [claimant: AddressLike, amount: BigNumberish];
  export type OutputTuple = [claimant: string, amount: bigint];
  export interface OutputObject {
    claimant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JuryVerdictSubmittedEvent {
  export type InputTuple = [
    verdictHash: BytesLike,
    winner: AddressLike,
    agentAAmount: BigNumberish,
    agentBAmount: BigNumberish,
    uri: string
  ];
  export type OutputTuple = [
    verdictHash: string,
    winner: string,
    agentAAmount: bigint,
    agentBAmount: bigint,
    uri: string
  ];
  export interface OutputObject {
    verdictHash: string;
    winner: string;
    agentAAmount: bigint;
    agentBAmount: bigint;
    uri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutcomeConfirmedEvent {
  export type InputTuple = [
    confirmer: AddressLike,
    proposer: AddressLike,
    outcomeHash: BytesLike
  ];
  export type OutputTuple = [
    confirmer: string,
    proposer: string,
    outcomeHash: string
  ];
  export interface OutputObject {
    confirmer: string;
    proposer: string;
    outcomeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutcomeProposedEvent {
  export type InputTuple = [
    proposer: AddressLike,
    outcomeHash: BytesLike,
    winner: AddressLike,
    agentAAmount: BigNumberish,
    agentBAmount: BigNumberish,
    uri: string
  ];
  export type OutputTuple = [
    proposer: string,
    outcomeHash: string,
    winner: string,
    agentAAmount: bigint,
    agentBAmount: bigint,
    uri: string
  ];
  export interface OutputObject {
    proposer: string;
    outcomeHash: string;
    winner: string;
    agentAAmount: bigint;
    agentBAmount: bigint;
    uri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CircleCourtAgreement extends BaseContract {
  connect(runner?: ContractRunner | null): CircleCourtAgreement;
  waitForDeployment(): Promise<this>;

  interface: CircleCourtAgreementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptAgreement: TypedContractMethod<[], [void], "nonpayable">;

  agentA: TypedContractMethod<[], [string], "view">;

  agentB: TypedContractMethod<[], [string], "view">;

  claimFunds: TypedContractMethod<[], [void], "nonpayable">;

  claimable: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  claimed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  confirmOutcome: TypedContractMethod<
    [proposer: AddressLike],
    [void],
    "nonpayable"
  >;

  disputeRaisedAt: TypedContractMethod<[], [bigint], "view">;

  escrowAmount: TypedContractMethod<[], [bigint], "view">;

  evidenceRulesHash: TypedContractMethod<[], [string], "view">;

  evidenceWindow: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  finalOutcomeHash: TypedContractMethod<[], [string], "view">;

  guidelinesHash: TypedContractMethod<[], [string], "view">;

  joinDeadlineAt: TypedContractMethod<[], [bigint], "view">;

  juryBridge: TypedContractMethod<[], [string], "view">;

  juryVerdictHash: TypedContractMethod<[], [string], "view">;

  markEscrowFunded: TypedContractMethod<[], [void], "nonpayable">;

  metadataUri: TypedContractMethod<[], [string], "view">;

  outcomes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, string, boolean] & {
        outcomeHash: string;
        winner: string;
        agentAAmount: bigint;
        agentBAmount: bigint;
        uri: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  proposeOutcome: TypedContractMethod<
    [
      outcomeHash: BytesLike,
      winner: AddressLike,
      agentAAmount: BigNumberish,
      agentBAmount: BigNumberish,
      uri: string
    ],
    [void],
    "nonpayable"
  >;

  raiseDispute: TypedContractMethod<[reasonUri: string], [void], "nonpayable">;

  statementHash: TypedContractMethod<[], [string], "view">;

  status: TypedContractMethod<[], [bigint], "view">;

  submitEvidence: TypedContractMethod<
    [evidenceUri: string],
    [void],
    "nonpayable"
  >;

  submitJuryVerdict: TypedContractMethod<
    [
      verdictHash: BytesLike,
      winner: AddressLike,
      agentAAmount: BigNumberish,
      agentBAmount: BigNumberish,
      uri: string
    ],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptAgreement"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agentA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "confirmOutcome"
  ): TypedContractMethod<[proposer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeRaisedAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrowAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "evidenceRulesHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "evidenceWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "finalOutcomeHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "guidelinesHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "joinDeadlineAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "juryBridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "juryVerdictHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "markEscrowFunded"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "metadataUri"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "outcomes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint, string, boolean] & {
        outcomeHash: string;
        winner: string;
        agentAAmount: bigint;
        agentBAmount: bigint;
        uri: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeOutcome"
  ): TypedContractMethod<
    [
      outcomeHash: BytesLike,
      winner: AddressLike,
      agentAAmount: BigNumberish,
      agentBAmount: BigNumberish,
      uri: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[reasonUri: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "statementHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<[evidenceUri: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitJuryVerdict"
  ): TypedContractMethod<
    [
      verdictHash: BytesLike,
      winner: AddressLike,
      agentAAmount: BigNumberish,
      agentBAmount: BigNumberish,
      uri: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgreementAccepted"
  ): TypedContractEvent<
    AgreementAcceptedEvent.InputTuple,
    AgreementAcceptedEvent.OutputTuple,
    AgreementAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceSubmitted"
  ): TypedContractEvent<
    EvidenceSubmittedEvent.InputTuple,
    EvidenceSubmittedEvent.OutputTuple,
    EvidenceSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "FundsClaimed"
  ): TypedContractEvent<
    FundsClaimedEvent.InputTuple,
    FundsClaimedEvent.OutputTuple,
    FundsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "JuryVerdictSubmitted"
  ): TypedContractEvent<
    JuryVerdictSubmittedEvent.InputTuple,
    JuryVerdictSubmittedEvent.OutputTuple,
    JuryVerdictSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OutcomeConfirmed"
  ): TypedContractEvent<
    OutcomeConfirmedEvent.InputTuple,
    OutcomeConfirmedEvent.OutputTuple,
    OutcomeConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "OutcomeProposed"
  ): TypedContractEvent<
    OutcomeProposedEvent.InputTuple,
    OutcomeProposedEvent.OutputTuple,
    OutcomeProposedEvent.OutputObject
  >;

  filters: {
    "AgreementAccepted(address)": TypedContractEvent<
      AgreementAcceptedEvent.InputTuple,
      AgreementAcceptedEvent.OutputTuple,
      AgreementAcceptedEvent.OutputObject
    >;
    AgreementAccepted: TypedContractEvent<
      AgreementAcceptedEvent.InputTuple,
      AgreementAcceptedEvent.OutputTuple,
      AgreementAcceptedEvent.OutputObject
    >;

    "DisputeRaised(address,string)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "EscrowFunded(address,uint256)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "EvidenceSubmitted(address,string)": TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
    EvidenceSubmitted: TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;

    "FundsClaimed(address,uint256)": TypedContractEvent<
      FundsClaimedEvent.InputTuple,
      FundsClaimedEvent.OutputTuple,
      FundsClaimedEvent.OutputObject
    >;
    FundsClaimed: TypedContractEvent<
      FundsClaimedEvent.InputTuple,
      FundsClaimedEvent.OutputTuple,
      FundsClaimedEvent.OutputObject
    >;

    "JuryVerdictSubmitted(bytes32,address,uint256,uint256,string)": TypedContractEvent<
      JuryVerdictSubmittedEvent.InputTuple,
      JuryVerdictSubmittedEvent.OutputTuple,
      JuryVerdictSubmittedEvent.OutputObject
    >;
    JuryVerdictSubmitted: TypedContractEvent<
      JuryVerdictSubmittedEvent.InputTuple,
      JuryVerdictSubmittedEvent.OutputTuple,
      JuryVerdictSubmittedEvent.OutputObject
    >;

    "OutcomeConfirmed(address,address,bytes32)": TypedContractEvent<
      OutcomeConfirmedEvent.InputTuple,
      OutcomeConfirmedEvent.OutputTuple,
      OutcomeConfirmedEvent.OutputObject
    >;
    OutcomeConfirmed: TypedContractEvent<
      OutcomeConfirmedEvent.InputTuple,
      OutcomeConfirmedEvent.OutputTuple,
      OutcomeConfirmedEvent.OutputObject
    >;

    "OutcomeProposed(address,bytes32,address,uint256,uint256,string)": TypedContractEvent<
      OutcomeProposedEvent.InputTuple,
      OutcomeProposedEvent.OutputTuple,
      OutcomeProposedEvent.OutputObject
    >;
    OutcomeProposed: TypedContractEvent<
      OutcomeProposedEvent.InputTuple,
      OutcomeProposedEvent.OutputTuple,
      OutcomeProposedEvent.OutputObject
    >;
  };
}
