/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CircleCourtRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agreementCount"
      | "agreements"
      | "createAgreement"
      | "juryBridge"
      | "owner"
      | "renounceOwnership"
      | "setJuryBridge"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgreementCreated"
      | "JuryBridgeUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agreementCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agreements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAgreement",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "juryBridge",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setJuryBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "agreementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agreements", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "juryBridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setJuryBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AgreementCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    agreement: AddressLike,
    agentA: AddressLike,
    agentB: AddressLike,
    amount: BigNumberish,
    joinDeadlineSeconds: BigNumberish,
    evidenceWindowSeconds: BigNumberish,
    statementHash: BytesLike,
    guidelinesHash: BytesLike,
    evidenceRulesHash: BytesLike,
    metadataUri: string
  ];
  export type OutputTuple = [
    id: bigint,
    agreement: string,
    agentA: string,
    agentB: string,
    amount: bigint,
    joinDeadlineSeconds: bigint,
    evidenceWindowSeconds: bigint,
    statementHash: string,
    guidelinesHash: string,
    evidenceRulesHash: string,
    metadataUri: string
  ];
  export interface OutputObject {
    id: bigint;
    agreement: string;
    agentA: string;
    agentB: string;
    amount: bigint;
    joinDeadlineSeconds: bigint;
    evidenceWindowSeconds: bigint;
    statementHash: string;
    guidelinesHash: string;
    evidenceRulesHash: string;
    metadataUri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JuryBridgeUpdatedEvent {
  export type InputTuple = [juryBridge: AddressLike];
  export type OutputTuple = [juryBridge: string];
  export interface OutputObject {
    juryBridge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CircleCourtRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CircleCourtRegistry;
  waitForDeployment(): Promise<this>;

  interface: CircleCourtRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agreementCount: TypedContractMethod<[], [bigint], "view">;

  agreements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        agreement: string;
        agentA: string;
        agentB: string;
        amount: bigint;
        joinDeadlineSeconds: bigint;
        evidenceWindowSeconds: bigint;
        statementHash: string;
        guidelinesHash: string;
        evidenceRulesHash: string;
        metadataUri: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  createAgreement: TypedContractMethod<
    [
      agentB: AddressLike,
      amount: BigNumberish,
      joinDeadlineSeconds: BigNumberish,
      evidenceWindowSeconds: BigNumberish,
      statementHash: BytesLike,
      guidelinesHash: BytesLike,
      evidenceRulesHash: BytesLike,
      metadataUri: string
    ],
    [string],
    "nonpayable"
  >;

  juryBridge: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setJuryBridge: TypedContractMethod<
    [juryBridge_: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agreementCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agreements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        agreement: string;
        agentA: string;
        agentB: string;
        amount: bigint;
        joinDeadlineSeconds: bigint;
        evidenceWindowSeconds: bigint;
        statementHash: string;
        guidelinesHash: string;
        evidenceRulesHash: string;
        metadataUri: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAgreement"
  ): TypedContractMethod<
    [
      agentB: AddressLike,
      amount: BigNumberish,
      joinDeadlineSeconds: BigNumberish,
      evidenceWindowSeconds: BigNumberish,
      statementHash: BytesLike,
      guidelinesHash: BytesLike,
      evidenceRulesHash: BytesLike,
      metadataUri: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "juryBridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setJuryBridge"
  ): TypedContractMethod<[juryBridge_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgreementCreated"
  ): TypedContractEvent<
    AgreementCreatedEvent.InputTuple,
    AgreementCreatedEvent.OutputTuple,
    AgreementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JuryBridgeUpdated"
  ): TypedContractEvent<
    JuryBridgeUpdatedEvent.InputTuple,
    JuryBridgeUpdatedEvent.OutputTuple,
    JuryBridgeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgreementCreated(uint256,address,address,address,uint256,uint256,uint256,bytes32,bytes32,bytes32,string)": TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;
    AgreementCreated: TypedContractEvent<
      AgreementCreatedEvent.InputTuple,
      AgreementCreatedEvent.OutputTuple,
      AgreementCreatedEvent.OutputObject
    >;

    "JuryBridgeUpdated(address)": TypedContractEvent<
      JuryBridgeUpdatedEvent.InputTuple,
      JuryBridgeUpdatedEvent.OutputTuple,
      JuryBridgeUpdatedEvent.OutputObject
    >;
    JuryBridgeUpdated: TypedContractEvent<
      JuryBridgeUpdatedEvent.InputTuple,
      JuryBridgeUpdatedEvent.OutputTuple,
      JuryBridgeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
